### ISSUE TITLE
After changing local library dir specto will not open

### ISSUE THREAD

**Issue by NiteBr33d** [mrknow/filmkodi#113]
Running on a firetvstick Spector version 2016.02.17.1
After changing  library to point to a save path on a windows machine. Try to launch Spector and is giving  
Error check log message. Can change library path back to default and Spector loads fine. This working in earlier versions.

**Comment by mrknow** [comment]
I check it out next week

**Comment by mrknow** [comment]
Fixed

**Comment by NiteBr33d** [comment]
This is still not working. On FireTV Stick. Specto 2016.05.8.7. I have my library on my pc. I go into specto, Settings,Library then TV. I change the path to point to my dir on my pc smb://Nite/Users/Nite/Desktop/Kodi/TVShows/ Then back to main screen to load Specto. It gives me Specto Fork Error Check Log For More Information and never opens Specto
