### ISSUE TITLE
SMB error fix (This is the solution)

### ISSUE THREAD

**Issue by Scotster** [mrknow/filmkodi#290]
I've been having some real trouble with the SMB shares not working in the latest version of specto so it was either SMB didn't work, or searching didn't work. I got fed up waiting for the answer so I dug around and managed to get mine working. Before you implement this solution be warned that the code you are about to change may be used for something important in your install. It seems meaningless to me but I don't understand the code THAT well.

Navigate to the following directory...

(.)Kodi\addons\plugin.video.specto\resources\lib\indexers

Open the file "navigator.py" in a text editor.

Scroll down till you see the following code:

`if not os.path.exists(movie_library):
            os.makedirs(movie_library)
        if not os.path.exists(tv_library):
            os.makedirs(tv_library)
        if not os.path.exists(tv_downloads):
            os.makedirs(tv_downloads)
        if not os.path.exists(movie_downloads):
            os.makedirs(movie_downloads)`

Remove that little lot then save the file. Note, putting a # before each line would probably work as well but served me no purpose.

Save the file and you're off and running again with your SMB shares intact.

Hope that helps till the issue is resolved.

**Comment by mrknow** [comment]
The problem is with defaults in settings.xml


`	`
Change lines 
`<category label="30950">`
`	<setting id="movie_downloads" type="folder" label="30951" default="special://userdata/addon_data/plugin.video.specto/Downloads/Movies" />`
`		<setting id="tv_downloads" type="folder" label="30952" default="special://userdata/addon_data/plugin.video.specto/Downloads/TVShows" />`
`	</category>`
To this with defaults=""
`<category label="30950">`
`	<setting id="movie_downloads" type="folder" label="30951" default="" />`
`		<setting id="tv_downloads" type="folder" label="30952" default="" />`
`	</category>`

Next go to  settings, and press button default , this will clean paths in download library.

Next select the appropriate directories

This will be fixed in new version in may ..

**Comment by xxcriticxx** [comment]
@mrknow you cant sleep?

**Comment by Scotster** [comment]
It didn't fix my issue but my previous solution is still in play. I changed the lines as per your edit but it did nothing so I also took my SMB shares out of the default "library" options. This still didn't work so I re-edited the navigator script to fix it again.

Are you debugging with an SMB share or just a custom share within the file system?

**Comment by Scotster** [comment]
Error code received when changing settings.xml to "" instead of "special://etc"....

`16:18:18 T:6252   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: (3, 'The system cannot find the path specified', '')
                                            Traceback (most recent call last):
                                              File "C:\Users\Scotster\AppData\Roaming\Kodi\addons\plugin.video.specto\default.py", line 126, in <module>
                                                navigator.navigator().root()
                                              File "C:\Users\Scotster\AppData\Roaming\Kodi\addons\plugin.video.specto\resources\lib\indexers\navigator.py", line 54, in __init__
                                                os.makedirs(movie_library)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: (3, 'The system cannot find the path specified', '')
                                            -->End of Python script error report<--
16:18:18 T:6828   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.specto/
16:18:18 T:6828   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.specto/) failed`

**Comment by ViperRunner** [comment]
Hi everyone,

Scotster, mrknow only said changes for the download directories, but we had mainly issues with the library directories, on mine i also changed the library directories on tsettings.xml:

From:
<category label="30920">
<setting id="movie_library" type="folder" label="30922" default="special://userdata/addon_data/plugin.video.specto/Movies" />
<setting id="tv_library" type="folder" label="30923" default="special://userdata/addon_data/plugin.video.specto/TVShows" />
To:
<category label="30920">
<setting id="movie_library" type="folder" label="30922" default="" />
<setting id="tv_library" type="folder" label="30923" default="" />

Still didn't have the time to test it on a samba share, but try and say if it resolved your issue!

Best regards

**Comment by Scotster** [comment]
I tried a few variations including setting all defaults to "". Doing so and then hitting default re-sets the default to "Special://" etc. If I then go in through the menu my only options are inside the "Special://" location, no option to select network or SMB etc.

If I then re-set the default share to SMB I get the same crashing log so it's definitely not working as it was previous. The new code in the navigation.py file is what's causing the conflict for me, it's all I can see that's changed from previous versions.

FWIW SMB shares were never set through the menu, they were always set via the settings.xml manually.

**Comment by mrknow** [comment]
SMB should work correctly . Check out this beta version
http://kodi.filmkodi.com/beta/plugin.video.specto/plugin.video.specto-2016.05.8.2.zip

**Comment by Scotster** [comment]
Still not working for me. Same error. There's no way to configure the library to access an SMB share so it has to be done via the Settings.XML file. When this is done, it crashes out with the above error.

**Comment by mrknow** [comment]
this issue is fixed in the new version

**Comment by Xitro01** [comment]
This issue is still current! The hotfix needs to be done after every update to get Specto working again!
