### ISSUE TITLE
Specto: in MY SPECTO the IMDB:TV WATCHLIST doesn't show info

### ISSUE THREAD

**Issue by LJHookem14** [mrknow/filmkodi#328]
If you import your IMDB watchlist and tv watchlist in TOOLS/SPECTO:LIBRARY, when you goto MY SPECTO to open the TV Watchlist for IMDb it does nothing. 

Thanks for getting everything else fixed though on Trakt a few updates back.

**Comment by mrknow** [comment]
#305 


in new version this is fixed (i think). New version will be released in monday 27.06.2016
Try add number as imdb user
http://www.imdb.com/user/urXXXXXX/

this should solve the problem

**Comment by kenmex** [comment]
This is not resolved.It really impresses me that this bug exists for so long and it has not been resolved yet.I do not want to believe that the developer is just ignoring it, but on the other hand I cannot believe that he is not able to fix it or does not have the time to do it.
Please either fix it or let the users know that it won't be fixed.
Thanks
